### ISSUE TITLE
Error when trying to view empty object of Class FIMatrix

### ISSUE THREAD

**Issue by titoeb** [TimToebrock/Project_Apriori#11]
data("Groceries")
err <- FindFrequentItemsets(Groceries, 0.3)
View(err)

leads to the error message
Error in if (more || nchar(output) > 80) { : 
  missing value where TRUE/FALSE needed

We did not create a "view" method (which maybe by itself is nice idea), but nevertheless an error should not occur when calling it.

**Comment by abuchmueller** [comment]
fixed in [63a4ddb](https://github.com/TimToebrock/Project_Apriori/commit/63a4ddb105d3b6a0f67e3d63c5e99e38fa552814). 

will also re-evaluate the behaviour of all methods when dealing with empty objects in a later commit
