### ISSUE TITLE
FrequentItemsets and AssociationRules functions currently broken

### ISSUE THREAD

**Issue by abuchmueller** [TimToebrock/Project_Apriori#2]
Since makeTransactionMatrix() now returns an object of its own class FrequentItemsets and AssociationRules do not work since they can't handle objects of this class yet

**Comment by abuchmueller** [comment]
makeTransactionMatrix has been reverted to it's old state (before classes). FrequentItemsets now works as before, however AssociationRules returns an object with 4 empty lists.

**Comment by abuchmueller** [comment]
`data("Groceries")`
`TransactionMatrix <- makeTransactionMatrix(Groceries)`
```
Rules <- AssociationRules(Itemsets=TransactionMatrix, minsupport = 0.01, 
                          minconfidence = 0.5, arefrequent = FALSE)
```


**vs using arules with same parameters**


`rules.arules <- apriori(Groceries, parameter = list(supp = 0.01, conf = 0.5));inspect(rules.arules)
`

**Comment by titoeb** [comment]
The bug was caused by DetSupport in the generation of the rules. Here I set the paramter same_item_num to true although the length of the items is not the same for the lhs of the rules. This paramter usually causes a faster calculation of the support if the length of the items is all the same.
