### ISSUE TITLE
AssociationRules returns rules below the support threshold

### ISSUE THREAD

**Issue by abuchmueller** [TimToebrock/Project_Apriori#5]
Bug occurs when using a frequent itemsets matrix (FIMatrix object) instead of an Transactionmatrix (TAMatrix object) when trying to calculate rules. AssociationRules will then use the support threshold of the FindfrequentItemsets function instead of it's own support threshold, example below:

```
data("Groceries")
TransactionMatrix <- makeTransactionMatrix(Groceries)
frequent_items <- FindFrequentItemsets(TransactionMatrix, 0.01)
Rules <- AssociationRules(Itemsets=TransactionMatrix, minsupport = 0.03, 
                          minconfidence = 0.4, arefrequent = FALSE)
fRules <- AssociationRules(FrequentItems = frequent_items, Itemsets = TransactionMatrix, minsupport = 0.03,
                          minconfidence = 0.4, arefrequent = TRUE)
```

Both Rules and fRules should contain the same rules because they have the same parameters (support 0.03 and confidence 0.4) but instead Rules.fast returns rules that have support >= 0.01 (instead of the specified 0.03)

**Comment by titoeb** [comment]
Thank you for the minimal example,
Bug fixed.
