### ISSUE TITLE
print() method for empty object of class Rules failes.

### ISSUE THREAD

**Issue by titoeb** [TimToebrock/Project_Apriori#7]

**Comment by titoeb** [comment]
Minimal Example producing the error:
data("Groceries")
groc_trans <- makeTransactionMatrix(Groceries)
rules_praprio <- AssociationRules(Itemsets =  groc_trans,minsupport = 0.1, minconfidence = 0.2, arefrequent = FALSE)
print(rules_praprio)

**Comment by abuchmueller** [comment]
this is fixed in [b0bd8d3](https://github.com/TimToebrock/Project_Apriori/commit/b0bd8d3c85cd67a3ee26d6250a77c51ea6f8f3b9). 
print now checks the length of an object before trying to print.
