### ISSUE TITLE
FindFrequentItemsets returns error when support threshold is too high

### ISSUE THREAD

**Issue by abuchmueller** [TimToebrock/Project_Apriori#8]
Running 
```
data("Groceries")
groc_trans <- makeTransactionMatrix(Groceries)
err <- FindFrequentItemsets(groc_trans, 0.3)
```
returns
```
 Error in sparseMatrix(i = vec_names, j = vec_names, giveCsparse = FALSE,  : 
  all(dims >= dims.min) is not TRUE 
```

a less cryptic error message stating that there's not a single itemset with this support threshold would be more appropriate.

**Comment by titoeb** [comment]
absolutely correct. issue fixed. Now the function returns an empty object of class FIMatrix and prints No Frequent Itemsets found with minimal support of 0.3 "
